
const A={players:{},standings:[],history:[],season:"",preSeason:false,updated:null,matchday:0};
const aliases={"arsenal":"Arsenal","arsenal fc":"Arsenal","aston villa":"Aston Villa","aston villa fc":"Aston Villa","bournemouth":"Bournemouth","afc bournemouth":"Bournemouth","bournemouth fc":"Bournemouth","brentford":"Brentford","brentford fc":"Brentford","brighton":"Brighton","brighton & hove albion":"Brighton","brighton and hove albion":"Brighton","chelsea":"Chelsea","chelsea fc":"Chelsea","coventry":"Coventry","coventry city":"Coventry","coventry city fc":"Coventry","crystal palace":"Crystal Palace","crystal palace fc":"Crystal Palace","everton":"Everton","everton fc":"Everton","fulham":"Fulham","fulham fc":"Fulham","hull":"Hull","hull city":"Hull","hull city afc":"Hull","ipswich":"Ipswich","ipswich town":"Ipswich","ipswich town fc":"Ipswich","leeds":"Leeds","leeds united":"Leeds","leeds united fc":"Leeds","liverpool":"Liverpool","liverpool fc":"Liverpool","man city":"Man City","manchester city":"Man City","manchester city fc":"Man City","man utd":"Man Utd","manchester united":"Man Utd","manchester united fc":"Man Utd","newcastle":"Newcastle","newcastle united":"Newcastle","newcastle united fc":"Newcastle","nottingham forest":"Nott'm Forest","nottingham forest fc":"Nott'm Forest","nott'm forest":"Nott'm Forest","sunderland":"Sunderland","sunderland afc":"Sunderland","spurs":"Spurs","tottenham":"Spurs","tottenham hotspur":"Spurs","tottenham hotspur fc":"Spurs"};
const names={"Arsenal":"Arsenal","Aston Villa":"Aston Villa","Bournemouth":"Bournemouth","Brentford":"Brentford","Brighton":"Brighton","Chelsea":"Chelsea","Coventry":"Coventry City","Crystal Palace":"Crystal Palace","Everton":"Everton","Fulham":"Fulham","Hull":"Hull City","Ipswich":"Ipswich Town","Leeds":"Leeds United","Liverpool":"Liverpool","Man City":"Manchester City","Man Utd":"Manchester United","Newcastle":"Newcastle United","Nott'm Forest":"Nottingham Forest","Sunderland":"Sunderland","Spurs":"Tottenham Hotspur"};
const norm=x=>String(x).toLowerCase().replace(/\s+/g," ").trim();
const key=x=>aliases[norm(x)]||x;
const cname=x=>names[key(x)]||key(x);
const esc=x=>String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const badge=x=>{let w=cname(x).replace(/[^A-Za-z ]/g,"").split(" ").filter(Boolean);return (w.length==1?w[0].slice(0,3):w.map(a=>a[0]).join("")).slice(0,3).toUpperCase()};
function score(rows){let actual=new Map(rows.map(r=>[key(r.team),+r.position]));return Object.entries(A.players).map(([name,preds])=>{let rr=preds.map(p=>{let a=actual.get(key(p.team));return{team:p.team,predicted:+p.position,actual:a??null,difference:a==null?null:Math.abs(+p.position-a)}});return{name,rows:rr,score:rr.reduce((s,r)=>s+(r.difference??0),0)}}).sort((a,b)=>a.score-b.score||a.name.localeCompare(b.name))}
function ranked(rows){let last=null,r=0;return rows.map((p,i)=>{if(p.score!==last){r=i+1;last=p.score}return{...p,rank:r}})}
const current=()=>ranked(score(A.standings));
function prior(){return A.history.length?ranked(score(A.history[A.history.length-1].standings||[])):null}
function mov(n,c,p){if(!p)return null;return (p.find(x=>x.name===n)?.rank??0)-(c.find(x=>x.name===n)?.rank??0)}
function dlt(n,c,p){if(!p)return null;return (c.find(x=>x.name===n)?.score??0)-(p.find(x=>x.name===n)?.score??0)}
function med(r){return r==1?"🥇":r==2?"🥈":r==3?"🥉":""}
function mv(x){return x==null?"—":x>0?"↑ "+x:x<0?"↓ "+Math.abs(x):"—"}
function dl(x){return x==null?"—":x<0?"▼ "+Math.abs(x):x>0?"▲ "+x:"—"}
function states(){let s=A.history.map(x=>({standings:x.standings||[],timestamp:x.timestamp||null}));if(!s.length||JSON.stringify(s[s.length-1].standings)!==JSON.stringify(A.standings))s.push({standings:A.standings,timestamp:A.updated});return s}
function chart(){let st=states();if(st.length<2)return`<div class="race-empty"><strong>The season race is ready to begin.</strong>Once the actual table changes, JIGSAW will record each distinct state and plot the four scores here.</div>`;let ns=Object.keys(A.players),ser={};ns.forEach(n=>ser[n]=[]);st.slice(-30).forEach(s=>score(s.standings).forEach(p=>ser[p.name].push(p.score)));let W=900,H=250,P=42,max=Math.max(...Object.values(ser).flat()),min=Math.min(...Object.values(ser).flat()),rg=Math.max(1,max-min),cols=["#55e2a0","#69a8ff","#f5cb62","#ff7388"],x=i=>P+i*(W-2*P)/Math.max(1,st.length-1),y=v=>H-P-(v-min)/rg*(H-2*P),svg=`<svg class="chart" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">`;ns.forEach((n,j)=>{let pts=ser[n].map((v,i)=>`${x(i)},${y(v)}`).join(" ");svg+=`<polyline class="chart-line" style="stroke:${cols[j]}" points="${pts}"/>`});svg+=`<text x="${P}" y="16" class="chart-axis">${max} pts</text><text x="${P}" y="${H-5}" class="chart-axis">Lower is better</text></svg>`;return`<div class="chart-wrap">${svg}</div><div class="race-legend">${ns.map((n,i)=>`<span class="legend-item"><span class="legend-dot" style="background:${cols[i]}"></span>${esc(n)}</span>`).join("")}</div>`}
function dashboard(){let c=current(),p=prior(),lead=c[0],last=c[c.length-1],best={d:-1},nailed={n:"",c:-1};c.forEach(x=>x.rows.forEach(r=>{if((r.difference??0)>best.d)best={d:r.difference,n:x.name,t:r.team}}));c.forEach(x=>{let n=x.rows.filter(r=>r.difference===0).length;if(n>nailed.c)nailed={n:x.name,c:n}});let changes=c.map(x=>({x,m:mov(x.name,c,p),d:dlt(x.name,c,p)})).filter(x=>x.m!==null).sort((a,b)=>b.m-a.m);document.querySelector("#dashboard").innerHTML=`<div class="section-head"><div><h2>The JIGSAW table</h2><p>Lower score wins. The table updates automatically as the Premier League changes.</p></div><span class="lock">🔒 Predictions locked</span></div><div class="dashboard-grid"><div class="card leader-card"><div class="leader-kicker">Current leader</div><div class="leader-name">${esc(lead.name)}</div><div class="leader-score">${lead.score}<span>points</span></div><div class="leader-sub">${A.preSeason?"Pre-season starting position":"Current position"} · 1st</div></div><div class="card rank-list">${c.map(x=>`<div class="rank-row"><div class="rank-no">${med(x.rank)||x.rank}</div><div class="rank-player">${esc(x.name)}</div><div class="rank-score">${x.score}</div><div class="movement">${mv(mov(x.name,c,p))}</div></div>`).join("")}</div></div><div class="insight-grid"><div class="card insight"><div class="insight-label">Gap to fourth</div><div class="insight-value">${last.score-lead.score} points</div><div class="insight-note">${esc(last.name)} currently sits ${last.score-lead.score} behind the leader.</div></div><div class="card insight"><div class="insight-label">Biggest miss</div><div class="insight-value">${best.d} places</div><div class="insight-note">${esc(best.n)} has ${esc(cname(best.t))} furthest from the prediction.</div></div><div class="card insight"><div class="insight-label">Most nailed</div><div class="insight-value">${esc(nailed.n)}</div><div class="insight-note">${nailed.c} of 20 clubs currently sit exactly where predicted.</div></div></div>${changes.length?`<div class="story-grid"><div class="card story"><div class="story-kicker">Biggest riser</div><div class="story-title">🟢 ${esc(changes[0].x.name)} ${mv(changes[0].m)}</div><div class="story-copy">${dl(changes[0].d)} points versus the previous snapshot.</div></div><div class="card story"><div class="story-kicker">Biggest faller</div><div class="story-title">🔴 ${esc(changes[changes.length-1].x.name)} ${mv(changes[changes.length-1].m)}</div><div class="story-copy">${dl(changes[changes.length-1].d)} points versus the previous snapshot.</div></div></div>`:""}<div class="card history-card"><div class="section-head"><div><h2>Score history</h2><p>A new snapshot is stored whenever the actual table changes.</p></div></div>${chart()}</div>`}
function race(){let c=current(),p=prior();document.querySelector("#race").innerHTML=`<div class="section-head"><div><h2>The season race</h2><p>Track the JIGSAW competition throughout ${esc(A.season)}.</p></div><span class="lock">${states().length} snapshot${states().length==1?"":"s"}</span></div><div class="race-grid"><div class="card race-card"><h3>Score race</h3><p>Lower is better.</p>${chart()}</div><div class="card race-card"><h3>Current form</h3><p>Change since the previous table snapshot.</p><div class="form-table">${c.map(x=>`<div class="form-row"><div class="form-rank">${med(x.rank)||x.rank}</div><div class="form-name">${esc(x.name)}</div><div>${dl(dlt(x.name,c,p))} pts</div><div>${mv(mov(x.name,c,p))} rank</div></div>`).join("")}</div></div></div>`}
function league(){document.querySelector("#table").innerHTML=`<div class="section-head"><div><h2>Premier League table</h2><p>${esc(A.season)} · Matchday ${A.matchday}</p></div></div>${A.preSeason?`<div class="notice">The season has not started. JIGSAW is using the configured starting order for this season rather than an arbitrary provider ordering.</div>`:""}<div class="table-wrap"><table><thead><tr><th>Pos</th><th>Club</th><th>P</th><th>W</th><th>D</th><th>L</th><th>GD</th><th>Pts</th></tr></thead><tbody>${A.standings.map(r=>`<tr><td class="pos">${r.position}</td><td class="club"><span class="club-mark">${esc(badge(r.team))}</span>${esc(cname(r.team))}</td><td>${r.played??0}</td><td>${r.won??0}</td><td>${r.drawn??0}</td><td>${r.lost??0}</td><td>${r.goalDifference??0}</td><td class="points">${r.points??0}</td></tr>`).join("")}</tbody></table></div>`}
function predictions(){let c=current();document.querySelector("#predictions").innerHTML=`<div class="section-head"><div><h2>Predictions</h2><p>See exactly where each prediction is currently winning or losing points.</p></div><select class="player-select" id="ps">${c.map(x=>`<option>${esc(x.name)}</option>`).join("")}</select></div><div id="pd"></div>`;document.querySelector("#ps").onchange=detail;detail()}
function detail(){let p=current().find(x=>x.name===document.querySelector("#ps").value);document.querySelector("#pd").innerHTML=`<div class="card detail-card"><div><div class="muted">Current score</div><div class="detail-score">${p.score}</div><div class="detail-meta">penalty points · ${p.rank} place</div></div><span class="lock">🔒 Prediction locked</span></div><div class="table-wrap"><table><thead><tr><th>Club</th><th>Prediction</th><th>Actual</th><th>Difference</th></tr></thead><tbody>${p.rows.map(r=>`<tr><td class="club">${esc(cname(r.team))}</td><td>${r.predicted}</td><td>${r.actual??"—"}</td><td class="${r.difference===0?"exact":(r.actual-r.predicted)>0?"positive":"negative"}"><strong>${r.difference??"—"}</strong></td></tr>`).join("")}</tbody></table></div>`}
async function load(){try{let [cfg,pred,st,h]=await Promise.all(["data/config.json","data/predictions.json","data/standings.json","data/history.json"].map(u=>fetch(u,{cache:"no-store"}).then(r=>r.ok?r.json():{})));A.players=pred.players||{};A.season=pred.season||cfg.currentSeason||st.season||"";A.standings=st.standings||[];A.history=h.snapshots||[];A.updated=st.lastUpdated;A.preSeason=!!st.preSeason;A.matchday=st.currentMatchday||0;document.title=`JIGSAW | ${A.season} Premier League Prediction Challenge`;document.querySelector("#seasonPill").textContent=A.season;document.querySelector("#footerSeason").textContent=A.season;document.querySelector("#heroSub").textContent=`The JIGSAW Premier League Prediction Challenge · ${A.season}`;document.querySelector("#competitionStatus").textContent=A.preSeason?"PRE-SEASON":"LIVE COMPETITION";document.querySelector("#statusText").textContent=A.preSeason?"Pre-season table":"Live league table";document.querySelector("#updatedText").textContent=A.updated?`Updated ${new Date(A.updated).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short"})}`:"Waiting for update";dashboard();race();league();predictions()}catch(e){console.error(e);document.querySelector("#dashboard").innerHTML='<div class="notice">The site could not load its data files. Please check the repository structure.</div>'}}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelector("#"+b.dataset.view).classList.add("active")});load();
