
const A={players:{},standings:[],history:[],archive:{seasons:{}},season:"",preSeason:false,finale:false,updated:null,matchday:0,gamesPlayed:0};
const aliases={"arsenal":"Arsenal","arsenal fc":"Arsenal","aston villa":"Aston Villa","aston villa fc":"Aston Villa","bournemouth":"Bournemouth","afc bournemouth":"Bournemouth","bournemouth fc":"Bournemouth","brentford":"Brentford","brentford fc":"Brentford","brighton":"Brighton","brighton & hove albion":"Brighton","brighton and hove albion":"Brighton","chelsea":"Chelsea","chelsea fc":"Chelsea","coventry":"Coventry","coventry city":"Coventry","coventry city fc":"Coventry","crystal palace":"Crystal Palace","crystal palace fc":"Crystal Palace","everton":"Everton","everton fc":"Everton","fulham":"Fulham","fulham fc":"Fulham","hull":"Hull","hull city":"Hull","hull city afc":"Hull","ipswich":"Ipswich","ipswich town":"Ipswich","ipswich town fc":"Ipswich","leeds":"Leeds","leeds united":"Leeds","leeds united fc":"Leeds","liverpool":"Liverpool","liverpool fc":"Liverpool","man city":"Man City","manchester city":"Man City","manchester city fc":"Man City","man utd":"Man Utd","manchester united":"Man Utd","manchester united fc":"Man Utd","newcastle":"Newcastle","newcastle united":"Newcastle","newcastle united fc":"Newcastle","nottingham forest":"Nott'm Forest","nottingham forest fc":"Nott'm Forest","nott'm forest":"Nott'm Forest","sunderland":"Sunderland","sunderland afc":"Sunderland","spurs":"Spurs","tottenham":"Spurs","tottenham hotspur":"Spurs"};
const names={"Arsenal":"Arsenal","Aston Villa":"Aston Villa","Bournemouth":"Bournemouth","Brentford":"Brentford","Brighton":"Brighton","Chelsea":"Chelsea","Coventry":"Coventry City","Crystal Palace":"Crystal Palace","Everton":"Everton","Fulham":"Fulham","Hull":"Hull City","Ipswich":"Ipswich Town","Leeds":"Leeds United","Liverpool":"Liverpool","Man City":"Manchester City","Man Utd":"Manchester United","Newcastle":"Newcastle United","Nott'm Forest":"Nottingham Forest","Sunderland":"Sunderland","Spurs":"Tottenham Hotspur"};
const norm=x=>String(x??"").toLowerCase().replace(/\s+/g," ").trim(), key=x=>aliases[norm(x)]||x, cname=x=>names[key(x)]||key(x);
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const badge=x=>{let w=cname(x).replace(/[^A-Za-z ]/g,"").split(" ").filter(Boolean);return (w.length==1?w[0].slice(0,3):w.map(a=>a[0]).join("")).slice(0,3).toUpperCase()};
const crest=r=>r?.crest||r?.crestUrl||r?.team?.crest||"";
const games=rows=>rows.length?Math.max(...rows.map(r=>+r.played||0)):0;
function score(rows){let actual=new Map(rows.map(r=>[key(r.team),+r.position]));return Object.entries(A.players).map(([name,preds])=>{let rr=preds.map(p=>{let a=actual.get(key(p.team));return{team:p.team,predicted:+p.position,actual:a??null,difference:a==null?null:Math.abs(+p.position-a)}});return{name,rows:rr,score:rr.reduce((s,r)=>s+(r.difference??0),0)}}).sort((a,b)=>a.score-b.score||a.name.localeCompare(b.name))}
function ranked(rows){let last=null,r=0;return rows.map((p,i)=>{if(p.score!==last){r=i+1;last=p.score}return{...p,rank:r}})}
const current=()=>ranked(score(A.standings));
function prior(){return A.history.length?ranked(score(A.history[A.history.length-1].standings||[])):null}
function mov(n,c,p){return p?(p.find(x=>x.name===n)?.rank??0)-(c.find(x=>x.name===n)?.rank??0):null}
function dlt(n,c,p){return p?(c.find(x=>x.name===n)?.score??0)-(p.find(x=>x.name===n)?.score??0):null}
function med(r){return r==1?"🥇":r==2?"🥈":r==3?"🥉":""}
function mv(x){return x==null?"—":x>0?"↑ "+x:x<0?"↓ "+Math.abs(x):"—"}
function dl(x){return x==null?"—":x<0?"▼ "+Math.abs(x):x>0?"▲ "+x:"—"}
function states(){let s=A.history.map(x=>({standings:x.standings||[],timestamp:x.timestamp||null}));if(!s.length||JSON.stringify(s[s.length-1].standings)!==JSON.stringify(A.standings))s.push({standings:A.standings,timestamp:A.updated});return s}
function crestImg(r){let u=crest(r);return u?`<img class="crest" src="${esc(u)}" alt="" onerror="this.style.display='none';this.nextElementSibling.style.display='inline-flex'">`:""} 
function clubMark(r){return `<span class="club-mark">${crestImg(r)}<span class="club-fallback">${esc(badge(r.team))}</span></span>`}
function tableRows(){return A.standings.map(r=>`<tr><td class="pos">${r.position}</td><td class="club">${clubMark(r)}${esc(cname(r.team))}</td><td>${r.played??0}</td><td>${r.won??0}</td><td>${r.drawn??0}</td><td>${r.lost??0}</td><td>${r.goalDifference??0}</td><td class="points">${r.points??0}</td></tr>`).join("")}
function dashboard(){let c=current(),p=prior(),lead=c[0],last=c[c.length-1];let exact=c.map(x=>({name:x.name,n:x.rows.filter(r=>r.difference===0).length})).sort((a,b)=>b.n-a.n)[0]||{name:"",n:0};let best={d:-1,n:"",t:""};c.forEach(x=>x.rows.forEach(r=>{if((r.difference??0)>best.d)best={d:r.difference,n:x.name,t:r.team}}));document.querySelector("#dashboard").innerHTML=`<div class="section-head"><div><h2>${A.finale?"🏆 Season Complete":"The JIGSAW table"}</h2><p>${A.finale?"The 38-game season is complete.  Final scores are now locked.":"Lower score wins.  The table updates automatically as the Premier League changes."}</p></div><span class="lock">${A.gamesPlayed}/38 games per team</span></div>${A.finale?finaleBanner(c):""}<div class="dashboard-grid"><div class="card leader-card"><div class="leader-kicker">${A.finale?"JIGSAW CHAMPION":"Current leader"}</div><div class="leader-name">${esc(lead?.name||"—")}</div><div class="leader-score">${lead?.score??"—"}<span>points</span></div><div class="leader-sub">${A.finale?"Final score":"Current position · 1st"}</div></div><div class="card rank-list">${c.map(x=>`<div class="rank-row"><div class="rank-no">${med(x.rank)||x.rank}</div><div class="rank-player">${esc(x.name)}</div><div class="rank-score">${x.score}</div><div class="movement">${mv(mov(x.name,c,p))}</div></div>`).join("")}</div></div><div class="insight-grid"><div class="card insight"><div class="insight-label">Gap to fourth</div><div class="insight-value">${last?last.score-lead.score:"—"} points</div><div class="insight-note">${last?esc(last.name):"—"} currently sits behind the leader.</div></div><div class="card insight"><div class="insight-label">Biggest miss</div><div class="insight-value">${best.d>=0?best.d:"—"} places</div><div class="insight-note">${best.n?esc(best.n)+" · "+esc(cname(best.t)):"No scored misses yet."}</div></div><div class="card insight"><div class="insight-label">Most nailed</div><div class="insight-value">${esc(exact.name||"—")}</div><div class="insight-note">${exact.n} of 20 clubs currently exactly match.</div></div></div>`}
function finaleBanner(c){let w=c[0];return `<div class="finale-banner"><div><span class="eyebrow">THE JIGSAW SEASON FINALE</span><h2>🏆 ${esc(w.name)} wins ${esc(A.season)}</h2><p>${w.score} penalty points.  The final Premier League table has been locked into JIGSAW history.</p></div><div class="finale-score">${w.score}<small>FINAL</small></div></div>`}
function race(){let c=current(),p=prior();document.querySelector("#race").innerHTML=`<div class="section-head"><div><h2>Season Race</h2><p>Follow the competition from opening day to the final table.</p></div><span class="lock">${A.history.length} snapshots</span></div><div class="card race-card"><div class="chart-placeholder"><strong>${A.history.length>1?"Score progression":"The season race is ready to begin."}</strong><span>${A.history.length>1?"Historical snapshots are retained throughout the season.":"Once the actual table changes, JIGSAW will plot the race."}</span></div><div class="form-table">${c.map(x=>`<div class="form-row"><div class="form-rank">${med(x.rank)||x.rank}</div><div class="form-name">${esc(x.name)}</div><div>${dl(dlt(x.name,c,p))} pts</div><div>${mv(mov(x.name,c,p))} rank</div></div>`).join("")}</div></div>`}
function league(){document.querySelector("#table").innerHTML=`<div class="section-head"><div><h2>Premier League</h2><p>${esc(A.season)} · ${A.gamesPlayed}/38 games per team</p></div><span class="lock">${A.finale?"FINAL TABLE":"LIVE TABLE"}</span></div>${A.preSeason?`<div class="notice">Pre-season starting order.  Competitive results have not yet begun.</div>`:""}<div class="table-wrap"><table><thead><tr><th>Pos</th><th>Club</th><th>P</th><th>W</th><th>D</th><th>L</th><th>GD</th><th>Pts</th></tr></thead><tbody>${tableRows()}</tbody></table></div>`}
function predictions(){let c=current();document.querySelector("#predictions").innerHTML=`<div class="section-head"><div><h2>Predictions</h2><p>See exactly where each prediction is currently winning or losing points.</p></div><select class="player-select" id="ps">${c.map(x=>`<option>${esc(x.name)}</option>`).join("")}</select></div><div id="pd"></div>`;document.querySelector("#ps").onchange=detail;detail()}
function detail(){let p=current().find(x=>x.name===document.querySelector("#ps").value);document.querySelector("#pd").innerHTML=`<div class="card detail-card"><div><div class="muted">Current score</div><div class="detail-score">${p.score}</div><div class="detail-meta">penalty points · ${p.rank} place</div></div><span class="lock">🔒 Prediction locked</span></div><div class="table-wrap"><table><thead><tr><th>Club</th><th>Prediction</th><th>Actual</th><th>Difference</th></tr></thead><tbody>${p.rows.map(r=>`<tr><td class="club">${esc(cname(r.team))}</td><td>${r.predicted}</td><td>${r.actual??"—"}</td><td class="${r.difference===0?"exact":(r.actual-r.predicted)<0?"positive":"negative"}"><strong>${r.difference??"—"}</strong></td></tr>`).join("")}</tbody></table></div>`}
function intel(){let c=current(),p=prior();if(A.preSeason){document.querySelector("#intel").innerHTML=`<div class="card intel-warm"><div class="eyebrow">JIGSAW INTEL</div><h2>The banter board is warming up.</h2><p>Once competitive football starts, this page will call out the best predictions, costly clubs, bold calls and movers.  No artificial pre-season drama.</p></div>`;return}let exact=[...c].sort((a,b)=>b.rows.filter(r=>r.difference===0).length-a.rows.filter(r=>r.difference===0).length)[0];let worst=[...c].sort((a,b)=>b.score-a.score)[0];let big=[];c.forEach(x=>x.rows.forEach(r=>{if(r.difference!=null)big.push({n:x.name,t:r.team,d:r.difference})}));big.sort((a,b)=>b.d-a.d);let movers=c.map(x=>({x,m:mov(x.name,c,p)})).filter(x=>x.m!==null).sort((a,b)=>b.m-a.m);document.querySelector("#intel").innerHTML=`<div class="section-head"><div><h2>JIGSAW Intel</h2><p>Automatic competition analysis.  No one gets to edit the narrative.</p></div></div><div class="intel-grid"><div class="card story"><div class="story-kicker">The Marksman</div><div class="story-title">🎯 ${esc(exact.name)}</div><div class="story-copy">${exact.rows.filter(r=>r.difference===0).length} exact calls.</div></div><div class="card story"><div class="story-kicker">The Big Call</div><div class="story-title">💥 ${esc(big[0]?.n||"—")}</div><div class="story-copy">${big[0]?`${esc(cname(big[0].t))}: ${big[0].d} places away.`:"No big misses yet."}</div></div><div class="card story"><div class="story-kicker">The Costly Club</div><div class="story-title">💷 ${esc(cname(big[0]?.t||"—"))}</div><div class="story-copy">The largest single prediction gap is ${big[0]?.d??0} points.</div></div><div class="card story"><div class="story-kicker">Under Pressure</div><div class="story-title">🔴 ${esc(worst.name)}</div><div class="story-copy">${worst.score} points currently — the highest score is under pressure.</div></div>${p&&movers.length?`<div class="card story"><div class="story-kicker">On The Charge</div><div class="story-title">🟢 ${esc(movers[0].x.name)}</div><div class="story-copy">${mv(movers[0].m)} places versus the previous snapshot.</div></div>`:""}</div>`}
function clubs(){let c=current();document.querySelector("#clubs").innerHTML=`<div class="section-head"><div><h2>Club Analysis</h2><p>See how every club is affecting the competition.</p></div><select class="player-select" id="cs">${A.standings.map(r=>`<option value="${esc(key(r.team))}">${esc(cname(r.team))}</option>`).join("")}</select></div><div id="cd"></div>`;document.querySelector("#cs").onchange=clubDetail;clubDetail()}
function clubDetail(){let k=document.querySelector("#cs").value,r=A.standings.find(x=>key(x.team)===k),c=current();let rows=c.map(p=>{let q=p.rows.find(x=>key(x.team)===k);return{name:p.name,pred:q?.predicted,actual:q?.actual,d:q?.difference}}).sort((a,b)=>a.d-b.d);document.querySelector("#cd").innerHTML=`<div class="card club-hero"><div>${clubMark(r)}</div><div><div class="muted">Current position</div><div class="detail-score">${r?.position??"—"}</div><h2>${esc(cname(k))}</h2></div></div><div class="table-wrap"><table><thead><tr><th>Player</th><th>Prediction</th><th>Actual</th><th>Impact</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.pred}</td><td>${x.actual??"—"}</td><td class="${x.d===0?"exact":(x.actual-x.pred)<0?"positive":"negative"}"><strong>${x.d??"—"}</strong></td></tr>`).join("")}</tbody></table></div>`}
function history(){let seasons=Object.entries(A.archive.seasons||{});document.querySelector("#history").innerHTML=`<div class="section-head"><div><h2>JIGSAW History</h2><p>Every completed season is retained permanently.</p></div></div>${seasons.length?`<div class="table-wrap"><table><thead><tr><th>Season</th><th>Winner</th><th>Final score</th><th>Players</th></tr></thead><tbody>${seasons.sort((a,b)=>b[0].localeCompare(a[0])).map(([s,x])=>`<tr><td><strong>${esc(s)}</strong></td><td>${esc(x.winner||"—")}</td><td>${x.finalScore??"—"}</td><td>${(x.results||[]).map(r=>`${esc(r.name)} ${r.score}`).join(" · ")}</td></tr>`).join("")}</tbody></table></div>`:`<div class="card intel-warm"><h2>First season underway.</h2><p>When ${esc(A.season)} reaches 38 games per team, the final standings will be stored here forever.</p></div>`}`}
function ultimate(){let seasons=Object.values(A.archive.seasons||{}),names=[...new Set([...(A.configPlayers||[]),...Object.keys(A.players)])];let totals={};names.forEach(n=>totals[n]=0);seasons.forEach(s=>(s.results||[]).forEach(r=>totals[r.name]=(totals[r.name]||0)+(+r.score||0)));Object.entries(A.players).forEach(([n])=>{if(!(n in totals))totals[n]=0});let rows=Object.entries(totals).sort((a,b)=>a[1]-b[1]);document.querySelector("#ultimate").innerHTML=`<div class="section-head"><div><h2>Ultimate Table</h2><p>Lowest aggregate score wins.  Every completed JIGSAW season counts.</p></div><span class="lock">${seasons.length} completed season${seasons.length===1?"":"s"}</span></div>${seasons.length?`<div class="table-wrap"><table><thead><tr><th>Pos</th><th>Player</th><th>Aggregate</th>${seasons.map(s=>`<th>${esc(s.season)}</th>`).join("")}</tr></thead><tbody>${rows.map((r,i)=>`<tr><td class="pos">${i+1}</td><td><strong>${esc(r[0])}</strong></td><td class="points"><strong>${r[1]}</strong></td>${seasons.map(s=>`<td>${(s.results||[]).find(x=>x.name===r[0])?.score??"—"}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`:`<div class="card intel-warm"><h2>The all-time race starts here.</h2><p>Once the first season is completed, the final Gary/Jimmy/Steve/Willie scores will be added to the Ultimate Table and retained for every future season.</p></div>`}`}
async function load(){try{let urls=["data/config.json","data/predictions.json","data/standings.json","data/history.json","data/season-archive.json"];let [cfg,pred,st,h,arc]=await Promise.all(urls.map(u=>fetch(u,{cache:"no-store"}).then(r=>r.ok?r.json():{})));A.configPlayers=cfg.playerOrder||[];A.players=pred.players||{};A.season=pred.season||cfg.currentSeason||st.season||"";A.standings=st.standings||[];A.history=h.snapshots||[];A.archive=arc&&arc.seasons?arc:{seasons:{}};A.updated=st.lastUpdated;A.preSeason=!!st.preSeason;A.gamesPlayed=games(A.standings);A.finale=A.gamesPlayed>=38;A.matchday=st.currentMatchday||0;document.title=`JIGSAW | ${A.season} Premier League Prediction Challenge`;document.querySelector("#seasonPill").textContent=A.season;document.querySelector("#footerSeason").textContent=A.season;document.querySelector("#heroSub").textContent=`The JIGSAW Premier League Prediction Challenge · ${A.season}`;document.querySelector("#competitionStatus").textContent=A.finale?"SEASON COMPLETE":A.preSeason?"PRE-SEASON":"LIVE COMPETITION";document.querySelector("#statusText").textContent=A.finale?"Final table":A.preSeason?"Pre-season table":"Live league table";document.querySelector("#updatedText").textContent=A.updated?`Updated ${new Date(A.updated).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short"})}`:"Waiting for update";dashboard();race();league();predictions();intel();clubs();history();ultimate()}catch(e){console.error(e);document.querySelector("#dashboard").innerHTML='<div class="notice">The site could not load its data files.  Please check the repository structure.</div>'}}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelector("#"+b.dataset.view).classList.add("active")});load();
